# Chart.yaml - This is the main metadata file for your Helm chart
# It contains information about the chart itself, not the application

# API version of the Helm chart (v2 is for Helm 3)
apiVersion: v2

# Name of the chart - this will be used when installing the chart
name: myapp-chart

# A brief description of what this chart does
description: A production-ready Helm chart for deploying a web application across Dev, Staging, and Production environments

# Chart type: 'application' means this deploys an application
# Alternative is 'library' for shared chart components
type: application

# Version of this Helm chart itself (not the app version)
# Increment this when you make changes to the chart
version: 1.0.0

# Version of the application being deployed
# This should match your application's version
appVersion: "1.0.0"

# Keywords help others find your chart
keywords:
  - kubernetes
  - webapp
  - microservice

# Maintainers of this chart
maintainers:
  - name: DevOps Team
    email: devops@example.com
